spring:
  application:
    name: LoginUsuario
  datasource:
    url: jdbc:mysql://localhost:3306/projetologin
    username: root
    password:

  jpa:
   show-sql: true
   hibernate:
     ddl-auto: update

